---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      customize:
        memory: 512
        cpus: 2

  - name: ubuntu-14.04
    driver_config:
      customize:
        memory: 512
        cpus: 2

  - name: debian-7.4
    driver_config:
      customize:
        memory: 512
        cpus: 2

suites:
  - name: mysql-zrm
    run_list:
      - recipe[fake::default]
    attributes:
      mysql:
        server_root_password: 'rootpass'
        server_debian_password: 'debpass'
        server_repl_password: 'replpass'
